/* Drop Tables */

DROP TABLE LIKE_IT CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE PRIVACY CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE ACCOUNT
(
	ID varchar2(256) NOT NULL,
	PW varchar2(256) NOT NULL,
	PFILE varchar2(200),
	SALT varchar2(256) NOT NULL,
	SSNUM varchar2(50) NOT NULL,
	PRIMARY KEY (ID)
);



CREATE TABLE BOARD
(
	BOARDNUM number NOT NULL,
	UDATE date NOT NULL,
	CONTENT varchar2(3500) NOT NULL,
	IMAGE varchar2(200),
	LIKECOUNT number NOT NULL,
	ID varchar2(256) NOT NULL,
	PRIMARY KEY (BOARDNUM)
);

CREATE TABLE LIKE_IT
(
	OWNER varchar2(256) NOT NULL,
	ISLIKE varchar2(64) NOT NULL,
	ID varchar2(256) NOT NULL,
	BOARDNUM number NOT NULL
);


CREATE TABLE PRIVACY
(
	SSNUM varchar2(50) NOT NULL,
	GENDER varchar2(20) NOT NULL,
	TEL varchar2(40) NOT NULL,
	EMAIL varchar2(256) NOT NULL,
	PRIMARY KEY (SSNUM)
);

CREATE TABLE REPLY
(
	UDATE date NOT NULL,
	CONTENT varchar2(3500) NOT NULL,
	REPLYNUM number NOT NULL,
	ID varchar2(256) NOT NULL,
	REF number NOT NULL,
	PRIMARY KEY (REPLYNUM)
);

CREATE TABLE RELATIONSHIP
(
	ID_1 varchar2(256) NOT NULL,
	ID_2 varchar2(256) NOT NULL,
	RELATION varchar2(128) NOT NULL
);


/* Create Foreign Keys */

ALTER TABLE BOARD
	ADD FOREIGN KEY (ID)
	REFERENCES ACCOUNT (ID)
;


ALTER TABLE LIKE_IT
	ADD FOREIGN KEY (ID)
	REFERENCES ACCOUNT (ID)
;


ALTER TABLE REPLY
	ADD FOREIGN KEY (ID)
	REFERENCES ACCOUNT (ID)
;


ALTER TABLE LIKE_IT
	ADD FOREIGN KEY (BOARDNUM)
	REFERENCES BOARD (BOARDNUM)
;

ALTER TABLE ACCOUNT
	ADD FOREIGN KEY (SSNUM)
	REFERENCES PRIVACY (SSNUM)
;

ALTER TABLE REPLY
	ADD FOREIGN KEY (REF)
	REFERENCES BOARD (BOARDNUM)
;

ALTER TABLE RELATIONSHIP
	ADD FOREIGN KEY (ID_1)
	REFERENCES ACCOUNT (ID)
;
ALTER TABLE RELATIONSHIP
	ADD FOREIGN KEY (ID_2)
	REFERENCES ACCOUNT (ID)
;
